/** Общие строки UI (web + mobile). */
export const strings = {
  common: {
    loading: 'Загрузка…',
    save: 'Сохранить',
    refresh: 'Обновить',
    cancel: 'Отмена',
    error: 'Ошибка',
  },
  auth: {
    loginTitle: 'Вход',
    registerTitle: 'Регистрация',
    email: 'Email',
    password: 'Пароль',
    displayName: 'Имя',
    orgName: 'Название организации',
    login: 'Войти',
    register: 'Зарегистрироваться',
    noAccount: 'Нет аккаунта?',
    hasAccount: 'Уже есть аккаунт?',
    toRegister: 'Создать',
    toLogin: 'Войти',
  },
  nav: {
    chat: 'Чат',
    connections: 'Подключения',
    profile: 'Профиль',
    marketplace: 'Каталог',
  },
  context: {
    org: 'Организация',
    group: 'Группа',
    workspace: 'Рабочая область',
    noWorkspace: 'Выберите рабочую область',
    pickOrg: 'Выберите организацию',
    pickGroup: 'Выберите группу',
    pickWorkspace: 'Выберите workspace',
  },
  app: {
    setupHint: 'Откройте меню внизу слева и выберите или создайте рабочую область.',
  },
  chat: {
    newChat: 'Новый чат',
    archived: 'Архив',
    archivedBadge: 'архив',
    send: 'Отправить',
    placeholder: 'Сообщение…',
    empty: 'Создайте новый чат или выберите существующий.',
    welcomeTitle: 'Чем могу помочь?',
    welcomeSub: 'Задайте вопрос или опишите задачу — ассистент ответит в этом workspace.',
    composerHint: 'Enter — отправить, Shift+Enter — новая строка',
    thinking: 'Ассистент печатает',
    untitled: 'Новый чат',
    noChats: 'Нет чатов',
    showArchived: 'Архив',
    archive: 'В архив',
    delete: 'Удалить',
    approve: 'Подтвердить',
    reject: 'Отклонить',
    deleteConfirm: 'Удалить этот чат безвозвратно?',
    hitlPrompt: 'Для выполнения действия нужно ваше подтверждение:',
    hitlApproved: 'Подтверждено. Выполняем действие…',
    hitlRejected: 'Действие отклонено.',
    toolDoneEmpty:
      'Действие выполнено. Если ожидали ссылку на Notion — проверьте подключение и базу в настройках инструментов.',
  },
  connections: {
    title: 'Подключения',
    empty: 'Нет установленных интеграций',
    health: 'Проверить',
    healthOk: 'Подключение в порядке',
    healthFail: (msg: string) => `Ошибка: ${msg || 'неизвестная'}`,
    deleted: 'Подключение удалено',
    edit: 'Изменить',
    delete: 'Удалить',
    deleteConfirm: 'Удалить подключение?',
    addMore: 'Добавить',
    secretKeep: 'Оставьте пустым, чтобы не менять',
    editTitle: (name: string) => `Изменить: ${name}`,
    saved: 'Сохранено',
  },
  mcp: {
    label: 'Название',
    marketplaceHint:
      'Выберите инструмент из каталога, укажите workspace и параметры подключения.',
    addTool: 'Добавить',
    catalogEmpty: 'В каталоге пока нет доступных инструментов.',
    install: (name: string) => `Установить ${name}`,
    installBtn: 'Установить',
    fieldRequired: 'Заполните поле',
    notionPickDatabase: 'База Notion',
    notionLoadingDatabases: 'Загрузка баз…',
    notionNoDatabases: 'Базы не найдены',
    notionSelectDatabase: 'Выберите базу',
    notionAutoIfEmpty: 'Если не выбрать — будет использована первая доступная база.',
  },
  profile: {
    title: 'Профиль',
    logout: 'Выйти',
    displayName: 'Отображаемое имя',
    orgName: 'Организация',
    account: 'Аккаунт',
    organizations: 'Организации',
    organizationsHint: 'Переключение между организациями',
    current: 'текущая',
    switchOrg: 'Перейти',
    organization: 'Текущая организация',
    orgSlug: 'Slug',
    plan: 'Тариф',
    groups: 'Группы',
    groupsEmpty: 'Нет групп',
    newGroupName: 'Название группы',
    createGroup: 'Создать группу',
    groupCreated: 'Группа создана',
    workspaces: 'Рабочие области',
    workspacesEmpty: 'Нет workspace',
    filterByGroup: 'Фильтр по группе',
    allGroups: 'Все группы',
    newWorkspaceName: 'Название workspace',
    createWorkspace: 'Создать workspace',
    workspaceCreated: 'Workspace создан',
    workspaceSaved: 'Workspace обновлён',
    createWorkspaceHint: 'Новый workspace в выбранной группе',
    statusActive: 'Активен',
    statusArchived: 'Архив',
    invites: 'Приглашения',
    invitesHint: 'Пригласите участников по email',
    inviteEmail: 'Email приглашённого',
    inviteOrgRole: 'Роль в организации',
    inviteGroup: 'Группа (опционально)',
    inviteNoGroup: 'Только организация',
    inviteGroupRole: 'Роль в группе',
    inviteOrgOnly: 'Вся организация',
    inGroup: 'в группе',
    inviteSend: 'Отправить приглашение',
    inviteCreated: 'Приглашение создано',
    inviteLinkLabel: 'Ссылка для принятия',
    inviteCopyLink: 'Копировать ссылку',
    inviteLinkCopied: 'Ссылка скопирована',
    inviteLinkCopyFailed: 'Не удалось скопировать',
    invitesEmpty: 'Нет активных приглашений',
    inviteRevoke: 'Отозвать',
    inviteRevokeConfirm: 'Отозвать приглашение?',
    inviteRevoked: 'Приглашение отозвано',
    access: 'Доступ',
    userId: 'User ID',
    orgId: 'Org ID',
    groupId: 'Group ID',
    permissions: 'Права',
    saved: 'Сохранено',
    orgSaved: 'Организация сохранена',
    roles: {
      member: 'Участник',
      admin: 'Администратор',
      viewer: 'Наблюдатель',
      owner: 'Владелец',
    } as Record<string, string>,
  },
  onboarding: {
    title: 'Подключите инструменты',
    subtitle: 'Установите хотя бы одну интеграцию, чтобы пользоваться чатом с инструментами.',
    skip: 'Пропустить',
    toMarketplace: 'Открыть каталог',
  },
} as const
