/** Общие строки UI (web + mobile). */
export const strings = {
  common: {
    loading: 'Загрузка…',
    save: 'Сохранить',
    refresh: 'Обновить',
    cancel: 'Отмена',
    error: 'Ошибка',
  },
  auth: {
    loginTitle: 'Вход в аккаунт',
    registerTitle: 'Регистрация',
    loginSubtitle: 'Войдите, чтобы продолжить работу с ассистентом и инструментами.',
    registerSubtitle: 'Создайте аккаунт и workspace для команды за пару минут.',
    email: 'Email',
    password: 'Пароль',
    displayName: 'Имя',
    orgName: 'Название организации',
    login: 'Войти',
    register: 'Создать аккаунт',
    noAccount: 'Нет аккаунта?',
    hasAccount: 'Уже есть аккаунт?',
    toRegister: 'Создать аккаунт',
    toLogin: 'Войти',
    orDivider: 'или',
    continueGoogle: 'Войти через Google',
    continueGithub: 'Войти через GitHub',
    signUpGoogle: 'Зарегистрироваться через Google',
    signUpGithub: 'Зарегистрироваться через GitHub',
  },
  nav: {
    menu: 'Меню',
    chat: 'Чат',
    mcp: 'Маркетплейс MCP',
    connections: 'Подключения',
    profile: 'Профиль',
    marketplace: 'Каталог',
  },
  header: {
    settings: 'Настройки',
  },
  context: {
    org: 'Организация',
    group: 'Группа',
    workspace: 'Рабочая область',
    noWorkspace: 'Выберите рабочую область',
    pickOrg: 'Выберите организацию',
    pickGroup: 'Выберите группу',
    pickWorkspace: 'Выберите workspace',
  },
  app: {
    backToChat: 'К чату',
    closeMenu: 'Закрыть меню',
    openContext: 'Организация, группа, workspace, профиль',
    contextUnset: 'Контекст не выбран',
    guest: 'Гость',
    setupHint: 'Нажмите на профиль внизу слева, чтобы выбрать организацию и workspace.',
    section: {
      chats: 'Чаты',
      tools: 'Инструменты',
      context: 'Организация и workspace',
      account: 'Аккаунт',
    },
  },
  chat: {
    newChat: 'Новый чат',
    archived: 'Архив',
    archivedBadge: 'архив',
    send: 'Отправить',
    placeholder: 'Сообщение…',
    empty: 'Создайте новый чат или выберите существующий.',
    welcomeTitle: 'Чем могу помочь?',
    welcomeSub: 'Задайте вопрос или опишите задачу — ассистент ответит в этом workspace.',
    composerHint: 'Enter — отправить, Shift+Enter — новая строка',
    thinking: 'Ассистент печатает',
    untitled: 'Новый чат',
    noChats: 'Нет чатов',
    showArchived: 'Архив',
    archive: 'В архив',
    delete: 'Удалить',
    approve: 'Подтвердить',
    approvePlan: 'Подтвердить план',
    reject: 'Отклонить',
    deleteConfirm: 'Удалить этот чат безвозвратно?',
    hitlPrompt: 'Для выполнения действия нужно ваше подтверждение:',
    hitlApproved: 'Подтверждено. Выполняем действие…',
    hitlRejected: 'Действие отклонено.',
    toolDoneEmpty:
      'Действие выполнено. Если ожидали ссылку на Notion — проверьте подключение и базу в настройках инструментов.',
  },
  connections: {
    title: 'Подключения',
    empty: 'Нет установленных интеграций в этом workspace.',
    health: 'Проверить',
    healthCheck: 'Проверить',
    healthOk: 'Подключение в порядке',
    healthFail: (msg: string) => `Ошибка: ${msg || 'неизвестная'}`,
    deleted: 'Подключение удалено',
    edit: 'Изменить',
    delete: 'Удалить',
    deleteConfirm: 'Удалить подключение?',
    addMore: 'Добавить',
    secretKeep: 'Оставьте пустым, чтобы не менять',
    editTitle: (name: string) => `Изменить: ${name}`,
    saved: 'Сохранено',
  },
  mcp: {
    label: 'Название',
    marketplaceHint:
      'Выберите инструмент из каталога, укажите workspace и параметры подключения.',
    addTool: 'Добавить',
    catalogEmpty: 'В каталоге пока нет доступных инструментов.',
    install: (name: string) => `Установить ${name}`,
    installBtn: 'Установить',
    fieldRequired: 'Заполните поле',
    notionPickDatabase: 'База Notion',
    notionLoadingDatabases: 'Загрузка баз…',
    notionNoDatabases: 'Базы не найдены',
    notionSelectDatabase: 'Выберите базу',
    notionAutoIfEmpty: 'Если не выбрать — будет использована первая доступная база.',
    trelloPickBoard: 'Доска Trello',
    trelloLoadingBoards: 'Загрузка досок…',
    trelloNoBoards: 'Доски не найдены',
    trelloSelectBoard: 'Выберите доску',
    trelloAutoIfEmpty: 'Если не выбрать — будет использована первая доступная доска.',
    trelloTokenHint:
      'После ввода API Key получите Token в Trello — ссылка подставит ваш ключ автоматически.',
    trelloGetToken: 'Получить Token в Trello',
    trelloTokenPaste:
      'После авторизации скопируйте token из адресной строки (после token=) и вставьте в поле Token ниже.',
  },
  profile: {
    title: 'Профиль',
    logout: 'Выйти',
    displayName: 'Отображаемое имя',
    orgName: 'Организация',
    account: 'Аккаунт',
    organizations: 'Организации',
    organizationsHint: 'Переключение между организациями',
    current: 'текущая',
    switchOrg: 'Перейти',
    organization: 'Текущая организация',
    orgSlug: 'Slug',
    plan: 'Тариф',
    groups: 'Группы',
    groupsEmpty: 'Нет групп',
    newGroupName: 'Название группы',
    createGroup: 'Создать группу',
    groupCreated: 'Группа создана',
    workspaces: 'Рабочие области',
    workspacesEmpty: 'Нет workspace',
    filterByGroup: 'Фильтр по группе',
    allGroups: 'Все группы',
    newWorkspaceName: 'Название workspace',
    createWorkspace: 'Создать workspace',
    workspaceCreated: 'Workspace создан',
    workspaceSaved: 'Workspace обновлён',
    createWorkspaceHint: 'Новый workspace в выбранной группе',
    statusActive: 'Активен',
    statusArchived: 'Архив',
    invites: 'Приглашения',
    invitesHint: 'Пригласите участников по email',
    inviteEmail: 'Email приглашённого',
    inviteOrgRole: 'Роль в организации',
    inviteGroup: 'Группа (опционально)',
    inviteNoGroup: 'Только организация',
    inviteGroupRole: 'Роль в группе',
    inviteOrgOnly: 'Вся организация',
    inGroup: 'в группе',
    inviteSend: 'Отправить приглашение',
    inviteCreated: 'Приглашение создано',
    inviteLinkLabel: 'Ссылка для принятия',
    inviteCopyLink: 'Копировать ссылку',
    inviteLinkCopied: 'Ссылка скопирована',
    inviteLinkCopyFailed: 'Не удалось скопировать',
    invitesEmpty: 'Нет активных приглашений',
    inviteRevoke: 'Отозвать',
    inviteRevokeConfirm: 'Отозвать приглашение?',
    inviteRevoked: 'Приглашение отозвано',
    access: 'Доступ',
    userId: 'User ID',
    orgId: 'Org ID',
    groupId: 'Group ID',
    permissions: 'Права',
    saved: 'Сохранено',
    orgSaved: 'Организация сохранена',
    roles: {
      member: 'Участник',
      admin: 'Администратор',
      viewer: 'Наблюдатель',
      owner: 'Владелец',
    } as Record<string, string>,
  },
  onboarding: {
    eyebrow: 'Первый запуск',
    title: 'Подключение инструментов',
    subtitle: 'Установите хотя бы одну интеграцию, чтобы пользоваться чатом с инструментами.',
    progress: 'Шаги онбординга',
    skip: 'Позже',
    start: 'Начать',
    next: 'Далее',
    back: 'Назад',
    finish: 'Перейти в чат',
    connectedCount: (count: number) => `Подключено инструментов: ${count}`,
    toMarketplace: 'Открыть каталог',
    steps: {
      welcome: 'Знакомство',
      connect: 'Подключение',
      configure: 'Настройка',
      chat: 'Чат',
    },
    welcomeLead:
      'Инструменты расширяют возможности ассистента: Notion, календари, CRM и другие сервисы. Подключите хотя бы один — и сможете выполнять действия прямо из чата.',
    welcomePoint1: 'Выберите инструмент в каталоге и укажите ключи или токены доступа.',
    welcomePoint2:
      'Проверьте подключение и при необходимости измените параметры (база Notion, название и т.д.).',
    welcomePoint3:
      'Опишите задачу в чате — ассистент предложит действие, вы подтвердите его одной кнопкой.',
    connectTitle: 'Подключите первый инструмент',
    connectHint:
      'Нажмите на карточку в каталоге, заполните форму и нажмите «Установить». Workspace уже выбран в вашем профиле.',
    configureTitle: 'Проверьте настройки',
    configureHint:
      'Откройте редактирование, чтобы изменить токен или целевую базу. Кнопка «Проверить» убедится, что сервис отвечает.',
    chatTitle: 'Как пользоваться в чате',
    chatHint:
      'Вернитесь в чат и опишите задачу обычным языком. Ассистент выберет подключённый инструмент и попросит подтверждение перед записью или изменением данных.',
    examplesLabel: 'Примеры запросов',
    example1: '«Создай в Notion страницу со списком задач на завтра»',
    example2: '«Найди в Notion заметки про проект Alpha и кратко перескажи»',
    hitlNote:
      'Перед опасными действиями (запись, удаление) появится запрос на подтверждение — нажмите «Подтвердить» или «Отклонить» под сообщением ассистента.',
  },
} as const
